version: '3.5'
services:
  # netcat:
  #   image: tomhjx/netcat:0.1.0-alpine-3.14.2
  #   cap_add:
  #     - ALL
  netcat:
    # image: golang:1.17.5
    build: 
      context: ./docker/build
      dockerfile: Dockerfile.go1.17.5-bullseye
    working_dir: /work/src
    environment:
      GOPROXY: "https://goproxy.cn,direct"
    cap_add:
      - ALL
    volumes:
      - .:/work
      - ~/Work/workspace/go:/go
networks:
  default:
    name: lab


